export const causesData = [
  {
    id: 1, 
    name: "Ocean Cleanup",
    description: "Fighting ocean plastic pollution and restoring marine ecosystems",
    longDescription: `The Ocean Cleanup is a non-profit organization developing advanced technologies to rid the world's oceans of plastic...`,
    imageSrc: "https://images.pexels.com/photos/1001682/pexels-photo-1001682.jpeg",
    category: "Environment",
    goal: 150,
    raised: 114,
    fundedPercentage: 76, // (114 / 150) * 100
    donors: 1245,
    website: "https://theoceancleanup.com/",
    walletAddress: '0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B',
    isActive: true,
    featured: false,
  },
  {
    id: 2, 
    name: "Reforestation Project",
    description: "Planting trees in deforested areas",
    longDescription: `The Reforestation Project is dedicated to restoring forests around the globe by planting trees.`,
    imageSrc: "https://images.pexels.com/photos/957024/forest-trees-perspective-bright-957024.jpeg",
    category: "Climate Action",
    goal: 70,
    raised: 58,
    fundedPercentage: 83, // (58 / 70) * 100
    donors: 850,
    website: "https://onetreeplanted.org/",
    walletAddress: '0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5',
    isActive: true,
    featured: true,
  },
  {
    id: 3, 
    name: "Clean Water Initiative",
    description: "Providing clean water to rural communities",
    longDescription: `The Clean Water Initiative works to bring clean and safe drinking water to communities in developing countries.`,
    imageSrc: "https://images.pexels.com/photos/1552941/pexels-photo-1552941.jpeg",
    category: "Humanitarian",
    goal: 50,
    raised: 32.5,
    fundedPercentage: 65, // (32.5 / 50) * 100
    donors: 980,
    website: "https://www.charitywater.org/",
    walletAddress: '0x8e23d11b519a4e2d443a6759034f71f1f2e2f3d6',
    isActive: true,
    featured: false,
  },
  {
    id: 4, 
    name: "Wildlife Conservation",
    description: "Protecting endangered species",
    longDescription: `The Wildlife Conservation fund is dedicated to protecting endangered species and their habitats.`,
    imageSrc: "https://images.pexels.com/photos/247431/pexels-photo-247431.jpeg",
    category: "Wildlife",
    goal: 100,
    raised: 42,
    fundedPercentage: 42,
    donors: 450,
    website: "https://www.worldwildlife.org/",
    walletAddress: '0x9d4a1f2e6b7c8d9e0f1a2b3c4d5e6f7g8h9i0j1k',
    isActive: true,
    featured: false,
  },
  {
    id: 5, 
    name: "Education For All",
    description: "Providing quality education to underprivileged children",
    longDescription: `Education For All aims to break the cycle of poverty by providing quality education to children in underserved communities.`,
    imageSrc: "https://images.pexels.com/photos/256541/pexels-photo-256541.jpeg",
    category: "Education",
    goal: 35,
    raised: 30.8,
    fundedPercentage: 88, // (30.8 / 35) * 100
    donors: 1500,
    website: "https://www.unicef.org/education",
    walletAddress: '0x1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t',
    isActive: true,
    featured: true,
  },
  {
    id: 6, 
    name: "Hunger Relief",
    description: "Providing meals to those in need",
    longDescription: `The Hunger Relief fund provides nutritious meals to families and individuals facing food insecurity.`,
    imageSrc: "https://images.pexels.com/photos/6995212/pexels-photo-6995212.jpeg",
    category: "Humanitarian",
    goal: 85,
    raised: 60.35,
    fundedPercentage: 71, // (60.35 / 85) * 100
    donors: 2100,
    website: "https://www.wfp.org/",
    walletAddress: '0x2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u',
    isActive: true,
    featured: false,
  },
  {
    id: 7, 
    name: "Renewable Energy",
    description: "Supporting clean energy projects",
    longDescription: `This fund supports the development and implementation of renewable energy projects, such as solar and wind farms.`,
    imageSrc: "https://images.pexels.com/photos/356036/pexels-photo-356036.jpeg",
    category: "Climate Action",
    goal: 250,
    raised: 147.5,
    fundedPercentage: 59, // (147.5 / 250) * 100
    donors: 300,
    website: "https://www.greenpeace.org/international/act/renewable-energy/",
    walletAddress: '0x3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v',
    isActive: false,
    featured: false,
  },
  {
    id: 8, 
    name: "Healthcare Access",
    description: "Expanding medical services to remote areas",
    longDescription: `Healthcare Access works to improve the health and well-being of people in remote areas.`,
    imageSrc: "https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg",
    category: "Healthcare",
    goal: 135,
    raised: 90.45,
    fundedPercentage: 67, // (90.45 / 135) * 100
    donors: 1100,
    website: "https://www.doctorswithoutborders.org/",
    walletAddress: '0x4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w',
    isActive: true,
    featured: true,
  }
];
